version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    on-failure: ABORT
    commands:
      - echo source version - $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Installing source NPM dependencies...
      - ls -la
      - npm install

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.js
    post_build:
      commands:
        - echo "Updating lambda Function..."
        - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip
        - echo "DONE!!"
