version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    on-failure: ABORT
    commands:
      - echo source version - $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo "Zipping deployment package..."
      - ls -la
      - zip -r9 github-to-lambda-demo.zip .
  post_build:
    commands:
        - echo "Updating lambda Function..."
        
        - aws deploy push --application-name github-to-lambda-demo --s3-location s3://astro-images/github-to-lambda-demo.zip --ignore-hidden-files
        - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://github-to-lambda-demo.zip
        - echo "DONE!!"

